// Generated by scripts/build-component.mjs from the component WIT. Do not edit.

/** @module Interface pydantic:monty/worker **/
export function dispatch(request: Request): DispatchResult
/**
 * # Variants
 *
 * ## `"continue"`
 *
 * ## `"shutdown"`
 */
export type Status = 'continue' | 'shutdown'
export interface NodePair {
  key: number
  value: number
}
export interface NamedTupleNode {
  typeName: string
  fieldNames: Array<string>
  items: Uint32Array
}
export interface DateNode {
  year: number
  month: number
  day: number
}
export interface DatetimeNode {
  year: number
  month: number
  day: number
  hour: number
  minute: number
  second: number
  microsecond: number
  offsetSeconds?: number
  timezoneName?: string
}
export interface TimeNode {
  hour: number
  minute: number
  second: number
  microsecond: number
  offsetSeconds?: number
  timezoneName?: string
  fold: number
}
export interface TimedeltaNode {
  days: number
  seconds: number
  microseconds: number
}
export interface TimezoneNode {
  offsetSeconds: number
  name?: string
}
export interface ExceptionValueNode {
  excType: string
  message?: string
}
export interface FileHandleNode {
  path: string
  mode: string
  position: bigint
}
export interface ClassTypeNode {
  name: string
  id: string
  hostDefined: boolean
  isDataclass: boolean
  attrs: Array<NodePair>
}
export interface ClassInstanceNode {
  classType: number
  instanceId: string
  attrs: Array<NodePair>
}
export interface FunctionNode {
  name: string
  docstring?: string
}
export interface CycleNode {
  identity: bigint
  placeholder: string
}
export type ValueNode =
  | ValueNodeEllipsis
  | ValueNodeNotImplemented
  | ValueNodeNone
  | ValueNodeBoolean
  | ValueNodeInteger
  | ValueNodeBigint
  | ValueNodeFloat
  | ValueNodeText
  | ValueNodeBytes
  | ValueNodeListValue
  | ValueNodeTupleValue
  | ValueNodeNamedTuple
  | ValueNodeDict
  | ValueNodeSet
  | ValueNodeFrozenSet
  | ValueNodeDate
  | ValueNodeDatetime
  | ValueNodeTime
  | ValueNodeTimedelta
  | ValueNodeTimezone
  | ValueNodeException
  | ValueNodeTypeName
  | ValueNodeClassType
  | ValueNodeBuiltinFunction
  | ValueNodePath
  | ValueNodeFileHandle
  | ValueNodeClassInstance
  | ValueNodeFunction
  | ValueNodeRepr
  | ValueNodeCycle
export interface ValueNodeEllipsis {
  tag: 'ellipsis'
}
export interface ValueNodeNotImplemented {
  tag: 'not-implemented'
}
export interface ValueNodeNone {
  tag: 'none'
}
export interface ValueNodeBoolean {
  tag: 'boolean'
  val: boolean
}
export interface ValueNodeInteger {
  tag: 'integer'
  val: bigint
}
export interface ValueNodeBigint {
  tag: 'bigint'
  val: string
}
export interface ValueNodeFloat {
  tag: 'float'
  val: number
}
export interface ValueNodeText {
  tag: 'text'
  val: string
}
export interface ValueNodeBytes {
  tag: 'bytes'
  val: Uint8Array
}
export interface ValueNodeListValue {
  tag: 'list-value'
  val: Uint32Array
}
export interface ValueNodeTupleValue {
  tag: 'tuple-value'
  val: Uint32Array
}
export interface ValueNodeNamedTuple {
  tag: 'named-tuple'
  val: NamedTupleNode
}
export interface ValueNodeDict {
  tag: 'dict'
  val: Array<NodePair>
}
export interface ValueNodeSet {
  tag: 'set'
  val: Uint32Array
}
export interface ValueNodeFrozenSet {
  tag: 'frozen-set'
  val: Uint32Array
}
export interface ValueNodeDate {
  tag: 'date'
  val: DateNode
}
export interface ValueNodeDatetime {
  tag: 'datetime'
  val: DatetimeNode
}
export interface ValueNodeTime {
  tag: 'time'
  val: TimeNode
}
export interface ValueNodeTimedelta {
  tag: 'timedelta'
  val: TimedeltaNode
}
export interface ValueNodeTimezone {
  tag: 'timezone'
  val: TimezoneNode
}
export interface ValueNodeException {
  tag: 'exception'
  val: ExceptionValueNode
}
export interface ValueNodeTypeName {
  tag: 'type-name'
  val: string
}
export interface ValueNodeClassType {
  tag: 'class-type'
  val: ClassTypeNode
}
export interface ValueNodeBuiltinFunction {
  tag: 'builtin-function'
  val: string
}
export interface ValueNodePath {
  tag: 'path'
  val: string
}
export interface ValueNodeFileHandle {
  tag: 'file-handle'
  val: FileHandleNode
}
export interface ValueNodeClassInstance {
  tag: 'class-instance'
  val: ClassInstanceNode
}
export interface ValueNodeFunction {
  tag: 'function'
  val: FunctionNode
}
export interface ValueNodeRepr {
  tag: 'repr'
  val: string
}
export interface ValueNodeCycle {
  tag: 'cycle'
  val: CycleNode
}
export interface Value {
  root: number
  nodes: Array<ValueNode>
}
export interface ValuePair {
  key: Value
  value: Value
}
export interface NamedValue {
  name: string
  value: Value
}
export interface ResourceLimits {
  maxDurationMicros?: bigint
  maxMemoryBytes?: bigint
  gcInterval?: bigint
  maxRecursionDepth?: bigint
  maxSuspensions?: bigint
}
/**
 * # Variants
 *
 * ## `"full"`
 *
 * ## `"concise"`
 *
 * ## `"azure"`
 *
 * ## `"json"`
 *
 * ## `"json-lines"`
 *
 * ## `"rdjson"`
 *
 * ## `"pylint"`
 *
 * ## `"gitlab"`
 *
 * ## `"github"`
 */
export type TypeCheckFormat =
  | 'full'
  | 'concise'
  | 'azure'
  | 'json'
  | 'json-lines'
  | 'rdjson'
  | 'pylint'
  | 'gitlab'
  | 'github'
export interface ConfigureRequest {
  scriptName: string
  limits?: ResourceLimits
  typeCheck: boolean
  typeCheckStubs?: string
  assertMessageAnnotations?: number
  typeCheckFormat: TypeCheckFormat
  typeCheckColor: boolean
}
export interface FeedRequest {
  code: string
  inputs: Array<NamedValue>
  skipTypeCheck: boolean
}
export interface RaisedError {
  excType: string
  message: string
}
export type CallResult =
  | CallResultReturnValue
  | CallResultError
  | CallResultPendingFuture
  | CallResultNotFound
  | CallResultNotHandled
export interface CallResultReturnValue {
  tag: 'return-value'
  val: Value
}
export interface CallResultError {
  tag: 'error'
  val: RaisedError
}
export interface CallResultPendingFuture {
  tag: 'pending-future'
  val: number
}
export interface CallResultNotFound {
  tag: 'not-found'
  val: string
}
export interface CallResultNotHandled {
  tag: 'not-handled'
}
export interface ResumeCallRequest {
  callId: number
  outcome: CallResult
}
export type NameLookupResult = NameLookupResultValue | NameLookupResultUndefined | NameLookupResultError
export interface NameLookupResultValue {
  tag: 'value'
  val: Value
}
export interface NameLookupResultUndefined {
  tag: 'undefined'
}
export interface NameLookupResultError {
  tag: 'error'
  val: RaisedError
}
export interface FutureResult {
  callId: number
  outcome: CallResult
}
export type Request =
  | RequestConfigure
  | RequestFeed
  | RequestResumeCall
  | RequestResumeNameLookup
  | RequestResumeFutures
  | RequestAbortFeed
  | RequestDump
  | RequestLoad
  | RequestReset
export interface RequestConfigure {
  tag: 'configure'
  val: ConfigureRequest
}
export interface RequestFeed {
  tag: 'feed'
  val: FeedRequest
}
export interface RequestResumeCall {
  tag: 'resume-call'
  val: ResumeCallRequest
}
export interface RequestResumeNameLookup {
  tag: 'resume-name-lookup'
  val: NameLookupResult
}
export interface RequestResumeFutures {
  tag: 'resume-futures'
  val: Array<FutureResult>
}
export interface RequestAbortFeed {
  tag: 'abort-feed'
  val: RaisedError
}
export interface RequestDump {
  tag: 'dump'
}
export interface RequestLoad {
  tag: 'load'
  val: Uint8Array
}
export interface RequestReset {
  tag: 'reset'
}
export interface StackFrame {
  filename: string
  line: number
  column: number
  endLine: number
  endColumn: number
  frameName?: string
  previewLine?: string
  hideCaret: boolean
  hideFrameName: boolean
}
export interface RaisedException {
  excType: string
  message: string
  traceback: string
  frames: Array<StackFrame>
}
export interface PrintEvent {
  stderr: boolean
  text: string
}
export interface FunctionCallEvent {
  functionName: string
  args: Array<Value>
  kwargs: Array<ValuePair>
  callId: number
  objectId?: string
}
export interface NameLookupEvent {
  name: string
  objectId?: string
}
export interface OsCallEvent {
  functionName: string
  args: Array<Value>
  kwargs: Array<ValuePair>
  callId: number
}
export type Event =
  | EventPrint
  | EventFunctionCall
  | EventOsCall
  | EventNameLookup
  | EventResolveFutures
  | EventComplete
  | EventError
  | EventTypingError
  | EventDumpResult
  | EventOk
  | EventFatalError
  | EventShutdown
export interface EventPrint {
  tag: 'print'
  val: PrintEvent
}
export interface EventFunctionCall {
  tag: 'function-call'
  val: FunctionCallEvent
}
export interface EventOsCall {
  tag: 'os-call'
  val: OsCallEvent
}
export interface EventNameLookup {
  tag: 'name-lookup'
  val: NameLookupEvent
}
export interface EventResolveFutures {
  tag: 'resolve-futures'
  val: Uint32Array
}
export interface EventComplete {
  tag: 'complete'
  val: Value
}
export interface EventError {
  tag: 'error'
  val: RaisedException
}
export interface EventTypingError {
  tag: 'typing-error'
  val: string
}
export interface EventDumpResult {
  tag: 'dump-result'
  val: Uint8Array
}
export interface EventOk {
  tag: 'ok'
}
export interface EventFatalError {
  tag: 'fatal-error'
  val: string
}
export interface EventShutdown {
  tag: 'shutdown'
  val: Uint8Array | undefined
}
export interface DispatchResult {
  status: Status
  events: Array<Event>
}
