//! Renders one crate's rustdoc JSON into a markdown page.
//!
//! Page shape: frontmatter, `# crate-name`, a hand-written intro (and the
//! crate's own `//!` docs where they aren't a README include), then one `##`
//! section per public root item in source order, with methods as `###`
//! subsections. Everything containing `<`/`{` goes inside ```rust fences or
//! backticks so the pages survive the docs site's MDX sanitizer untouched.

use std::fmt::Write;

use rustdoc_types::{Crate, Id, Impl, Item, ItemEnum, Module};

use crate::{
    CrateConfig,
    docs_md::process_docs,
    sig::{fn_decl, item_decl, path_str, type_str},
    symbols::{SymbolMap, resolve_root_entry},
};

/// Renders the complete page for one crate.
pub fn render_page(cfg: &CrateConfig, krate: &Crate, symbols: &SymbolMap) -> String {
    let ctx = Ctx {
        krate,
        symbols,
        rustdoc_name: cfg.name.replace('-', "_"),
    };
    let mut out = format!(
        "---\n# @generated by `make generate-api-docs` — DO NOT EDIT.\ntitle: {name}\n---\n\n# {name}\n\n{intro}\n",
        name = cfg.name,
        intro = cfg.intro,
    );
    let root = &krate.index[&krate.root];
    if cfg.render_crate_docs
        && let Some(docs) = &root.docs
    {
        out.push('\n');
        out.push_str(&ctx.docs(docs, 1, root));
        out.push('\n');
    }
    let ItemEnum::Module(module) = &root.inner else {
        panic!("crate root of {} is not a module", cfg.name)
    };
    let mut external = Vec::new();
    for entry in &module.items {
        match resolve_root_entry(krate, *entry) {
            Some((name, item)) => ctx.render_item(&mut out, &name, item, 2),
            None => {
                if let ItemEnum::Use(use_) = &krate.index[entry].inner {
                    let defining = use_.id.and_then(|id| krate.paths.get(&id));
                    let source_crate = defining.and_then(|d| d.path.first().cloned());
                    // when the defining crate has a page of its own, link there
                    let url = use_.id.and_then(|id| symbols.resolve(&ctx.rustdoc_name, krate, id));
                    external.push((use_.name.clone(), source_crate, url));
                }
            }
        }
    }
    if !external.is_empty() {
        out.push_str("\n## Re-exports\n\n");
        for (name, source_crate, url) in external {
            let name = match url {
                Some(url) => format!("[`{name}`]({url})"),
                None => format!("`{name}`"),
            };
            match source_crate {
                Some(source) => writeln!(out, "- {name} — re-exported from `{source}`.").unwrap(),
                None => writeln!(out, "- {name}.").unwrap(),
            }
        }
    }
    out
}

/// Shared rendering context: the crate being rendered plus link resolution.
struct Ctx<'a> {
    krate: &'a Crate,
    symbols: &'a SymbolMap,
    rustdoc_name: String,
}

impl Ctx<'_> {
    /// Renders one item section at `level` (`##` for root items) under the
    /// name it is re-exported as.
    fn render_item(&self, out: &mut String, name: &str, item: &Item, level: usize) {
        if let ItemEnum::Module(module) = &item.inner {
            self.render_module(out, name, item, module, level);
            return;
        }
        writeln!(out, "\n{} {name}\n", "#".repeat(level)).unwrap();
        writeln!(out, "```rust\n{}\n```", item_decl(name, item, self.krate)).unwrap();
        Self::push_deprecation(out, item);
        if let Some(docs) = &item.docs {
            writeln!(out, "\n{}", self.docs(docs, level, item)).unwrap();
        }
        match &item.inner {
            ItemEnum::Struct(s) => self.render_impls(out, name, &s.impls, level),
            ItemEnum::Enum(e) => self.render_impls(out, name, &e.impls, level),
            ItemEnum::Trait(t) => self.render_assoc_docs(out, &t.items, level),
            _ => {}
        }
    }

    /// A public module: its docs, then its items one heading level down.
    fn render_module(&self, out: &mut String, name: &str, item: &Item, module: &Module, level: usize) {
        writeln!(out, "\n{} {name}\n", "#".repeat(level)).unwrap();
        writeln!(out, "```rust\npub mod {name};\n```").unwrap();
        if let Some(docs) = &item.docs {
            writeln!(out, "\n{}", self.docs(docs, level, item)).unwrap();
        }
        for entry in &module.items {
            if let Some((child_name, child)) = resolve_root_entry(self.krate, *entry) {
                self.render_item(out, &child_name, child, level + 1);
            }
        }
    }

    /// Method subsections from inherent impls (ordered by source position),
    /// then a one-line list of implemented traits.
    fn render_impls(&self, out: &mut String, name: &str, impls: &[Id], level: usize) {
        let mut inherent: Vec<&Item> = Vec::new();
        let mut traits: Vec<String> = Vec::new();
        for impl_id in impls {
            let impl_item = &self.krate.index[impl_id];
            let ItemEnum::Impl(impl_) = &impl_item.inner else {
                continue;
            };
            match &impl_.trait_ {
                None => inherent.push(impl_item),
                Some(trait_) => {
                    if !impl_.is_synthetic && !impl_.is_negative && impl_.blanket_impl.is_none() {
                        traits.push(path_str(trait_));
                    }
                }
            }
        }
        inherent.sort_by_key(|item| item.span.as_ref().map(|s| (s.filename.clone(), s.begin)));
        for impl_item in inherent {
            let ItemEnum::Impl(impl_) = &impl_item.inner else {
                unreachable!()
            };
            self.render_methods(out, name, impl_, level);
        }
        traits.sort();
        traits.dedup();
        if !traits.is_empty() {
            let list: Vec<String> = traits.iter().map(|t| format!("`{t}`")).collect();
            writeln!(out, "\nImplements: {}.", list.join(", ")).unwrap();
        }
    }

    /// The methods (and associated consts) of one inherent impl block.
    fn render_methods(&self, out: &mut String, type_name: &str, impl_: &Impl, level: usize) {
        for method_id in &impl_.items {
            let method = &self.krate.index[method_id];
            let Some(method_name) = method.name.as_deref() else {
                continue;
            };
            let decl = match &method.inner {
                ItemEnum::Function(f) => fn_decl(method_name, f, ""),
                ItemEnum::AssocConst { type_, value, .. } => {
                    let value = value.as_deref().unwrap_or("_");
                    format!("pub const {method_name}: {} = {value};", type_str(type_))
                }
                inner => panic!(
                    "unhandled impl item {type_name}::{method_name}: {:?}",
                    inner.item_kind()
                ),
            };
            writeln!(out, "\n{} {method_name}\n", "#".repeat(level + 1)).unwrap();
            writeln!(out, "```rust\n{decl}\n```").unwrap();
            Self::push_deprecation(out, method);
            if let Some(docs) = &method.docs {
                writeln!(out, "\n{}", self.docs(docs, level + 1, method)).unwrap();
            }
        }
    }

    /// Prose docs for a trait's associated items; their signatures already
    /// appear in the trait's declaration fence.
    fn render_assoc_docs(&self, out: &mut String, items: &[Id], level: usize) {
        for assoc_id in items {
            let assoc = &self.krate.index[assoc_id];
            let (Some(assoc_name), Some(docs)) = (assoc.name.as_deref(), &assoc.docs) else {
                continue;
            };
            writeln!(out, "\n{} {assoc_name}\n", "#".repeat(level + 1)).unwrap();
            writeln!(out, "{}", self.docs(docs, level + 1, assoc)).unwrap();
        }
    }

    fn push_deprecation(out: &mut String, item: &Item) {
        if let Some(deprecation) = &item.deprecation {
            let note = deprecation.note.as_deref().unwrap_or("");
            writeln!(out, "\n**Deprecated.** {note}").unwrap();
        }
    }

    /// Item docs, processed for this page.
    fn docs(&self, docs: &str, heading_level: usize, item: &Item) -> String {
        process_docs(
            docs,
            heading_level,
            &item.links,
            &self.rustdoc_name,
            self.krate,
            self.symbols,
        )
    }
}
